//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MirageIslandPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MirageIslandPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PluginName = Wundereiland Tool
        ///MirageIsland = Wundereiland (Route 130)
        ///WillLetYouSeeMirageIsland = Pokémon die dich Wundereiland sehen lassen
        ///Seed = Seed:
        ///SeedExplanation = Seed muss den letzten 4 Zeichen der PID eines Pokémon entsprechen.
        ///Save = Speichern
        ///Box = Box
        ///Party = Team
        ///Slot = Slot.
        /// </summary>
        public static string lang_de {
            get {
                return ResourceManager.GetString("lang_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PluginName = Mirage Island Tool
        ///MirageIsland = Mirage Island (Route 130)
        ///WillLetYouSeeMirageIsland = Pokémon that will let you see Mirage Island
        ///Seed = Seed:
        ///SeedExplanation = Seed has to match the last 4 characters of your Pokémon&apos;s PID.
        ///Save = Save
        ///Box = Box
        ///Party = Party
        ///Slot = Slot.
        /// </summary>
        public static string lang_es {
            get {
                return ResourceManager.GetString("lang_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PluginName = Mirage Island Tool
        ///MirageIsland = Mirage Island (Route 130)
        ///WillLetYouSeeMirageIsland = Pokémon that will let you see Mirage Island
        ///Seed = Seed:
        ///SeedExplanation = Seed has to match the last 4 characters of your Pokémon&apos;s PID.
        ///Save = Save
        ///Box = Box
        ///Party = Party
        ///Slot = Slot.
        /// </summary>
        public static string lang_fr {
            get {
                return ResourceManager.GetString("lang_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PluginName = Mirage Island Tool
        ///MirageIsland = Mirage Island (Route 130)
        ///WillLetYouSeeMirageIsland = Pokémon that will let you see Mirage Island
        ///Seed = Seed:
        ///SeedExplanation = Seed has to match the last 4 characters of your Pokémon&apos;s PID.
        ///Save = Save
        ///Box = Box
        ///Party = Party
        ///Slot = Slot.
        /// </summary>
        public static string lang_it {
            get {
                return ResourceManager.GetString("lang_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PluginName = Mirage Island Tool
        ///MirageIsland = Mirage Island (Route 130)
        ///WillLetYouSeeMirageIsland = Pokémon that will let you see Mirage Island
        ///Seed = Seed:
        ///SeedExplanation = Seed has to match the last 4 characters of your Pokémon&apos;s PID.
        ///Save = Save
        ///Box = Box
        ///Party = Party
        ///Slot = Slot.
        /// </summary>
        public static string lang_ja {
            get {
                return ResourceManager.GetString("lang_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PluginName = Mirage Island Tool
        ///MirageIsland = Mirage Island (Route 130)
        ///WillLetYouSeeMirageIsland = Pokémon that will let you see Mirage Island
        ///Seed = Seed:
        ///SeedExplanation = Seed has to match the last 4 characters of your Pokémon&apos;s PID.
        ///Save = Save
        ///Box = Box
        ///Party = Party
        ///Slot = Slot.
        /// </summary>
        public static string lang_ko {
            get {
                return ResourceManager.GetString("lang_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PluginName = Mirage Island Tool
        ///MirageIsland = Mirage Island (Route 130)
        ///WillLetYouSeeMirageIsland = Pokémon that will let you see Mirage Island
        ///Seed = Seed:
        ///SeedExplanation = Seed has to match the last 4 characters of your Pokémon&apos;s PID.
        ///Save = Save
        ///Box = Box
        ///Party = Party
        ///Slot = Slot.
        /// </summary>
        public static string lang_zh {
            get {
                return ResourceManager.GetString("lang_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PluginName = Mirage Island Tool
        ///MirageIsland = Mirage Island (Route 130)
        ///WillLetYouSeeMirageIsland = Pokémon that will let you see Mirage Island
        ///Seed = Seed:
        ///SeedExplanation = Seed has to match the last 4 characters of your Pokémon&apos;s PID.
        ///Save = Save
        ///Box = Box
        ///Party = Party
        ///Slot = Slot.
        /// </summary>
        public static string lang_zh2 {
            get {
                return ResourceManager.GetString("lang_zh2", resourceCulture);
            }
        }
    }
}
